// Workshop-only material. Existing word and phrase sets remain unchanged.
(function () {
  const pair=(ru,en)=>({ru,en});
  const entries=[
    ['dictionary','base','Словарная форма','Dictionary form','Действие вообще, привычка или будущее в простом стиле. Это форма из словаря.','General, habitual or future actions in plain speech. This is the dictionary entry.','Берём глагол без изменений. Простая форма — не только настоящее время.','Use the verb unchanged. Non-past can describe habits or the future.','あした、ほんを よむ。','Завтра прочитаю книгу.','I will read a book tomorrow.'],
    ['masu','base','ます — вежливо','Masu — polite','Вежливо сообщить о привычке или будущем действии.','Politely describe a habit or future action.','Основа ます + ます: よむ → よみ → よみます; たべる → たべ → たべます.','Masu stem + ます: よむ → よみ → よみます; たべる → たべ → たべます.','まいにち、ほんを よみます。','Каждый день читаю книгу.','I read a book every day.'],
    ['masen','base','ません — вежливое отрицание','Masen — polite negative','Не делаю / не буду делать.','Do not / will not do.','Основа ます + ません. Не добавляй ない после ます.','Masu stem + ません. Do not add ない after ます.','きょうは コーヒーを のみません。','Сегодня не буду пить кофе.','I will not drink coffee today.'],
    ['mashita','base','ました — вежливое прошедшее','Mashita — polite past','Действие произошло.','An action happened.','Основа ます + ました.','Masu stem + ました.','きのう、ほんを よみました。','Вчера прочитал книгу.','I read a book yesterday.'],
    ['masen-deshita','base','ませんでした — не сделал','Masen deshita — polite past negative','Вежливое отрицание в прошлом.','Politely describe something that did not happen.','Основа ます + ませんでした.','Masu stem + ませんでした.','きのう、テレビを みませんでした。','Вчера не смотрел телевизор.','I did not watch TV yesterday.'],
    ['nai','base','ない — простое отрицание','Nai — plain negative','Не делать в простом стиле. Основа для просьб и обязанности.','Plain negative; a base for negative requests and obligation.','Ⅰ: последний слог в ряд あ + ない (う → わない). Ⅱ: る → ない. Ⅲ: する → しない; くる → こない. ある → ない.','Ⅰ: final kana to the a-row + ない (う → わない). Ⅱ: る → ない. Ⅲ: する → しない; くる → こない. ある → ない.','きょうは おさけを のまない。','Сегодня не пью алкоголь.','I am not drinking alcohol today.'],
    ['nakatta','base','なかった — не сделал','Nakatta — plain past negative','Простое отрицание в прошлом.','Plain past negative.','В ない-форме замени последнее い на かった: よまない → よまなかった.','Change final い in the nai-form to かった: よまない → よまなかった.','きのう、ほんを よまなかった。','Вчера не читал книгу.','I did not read a book yesterday.'],
    ['te','te','て／で — соединительная форма','Te / de — connecting form','Соединяет действия и служит основой конструкций. Сама по себе не означает прошедшее время.','Connects actions and builds other expressions. It is not a past tense by itself.','Ⅰ: う・つ・る → って; む・ぶ・ぬ → んで; く → いて; ぐ → いで; す → して. Ⅱ: る → て. Ⅲ: する → して; くる → きて. Исключение: いく → いって.','Ⅰ: う・つ・る → って; む・ぶ・ぬ → んで; く → いて; ぐ → いで; す → して. Ⅱ: る → て. Ⅲ: する → して; くる → きて. Exception: いく → いって.','ほんを よんで、ねます。','Почитаю книгу и лягу спать.','I will read a book and go to bed.'],
    ['ta','base','た／だ — простое прошедшее','Ta / da — plain past','Действие произошло или завершилось.','An action happened or was completed.','Сначала て-форма, затем て → た, で → だ: かいて → かいた; よんで → よんだ.','First make the te-form, then て → た and で → だ: かいて → かいた; よんで → よんだ.','きのう、ほんを よんだ。','Вчера прочитал книгу.','I read a book yesterday.'],
    ['tai','wish','たい — хочу сделать','Tai — want to do','Говорим о своём желании; в вопросе — о желании собеседника.','Express your own desire, or ask about the listener’s desire.','Основа ます + たい: たべます → たべたい. Не たべるたい и не たべてたい. О чужих желаниях обычно говорят иначе: например, たがっている.','Masu stem + たい: たべます → たべたい. Not たべるたい or たべてたい. Third-person wishes usually need another expression, such as たがっている.','にほんへ いきたいです。','Хочу поехать в Японию.','I want to go to Japan.'],
    ['takunai','wish','たくない — не хочу','Takunai — do not want to','Отрицаем желание, а не само действие.','Negate the desire, not the action itself.','たい изменяется как い-прилагательное: たい → たくない.','たい conjugates like an i-adjective: たい → たくない.','きょうは でかけたくないです。','Сегодня не хочу выходить из дома.','I do not want to go out today.'],
    ['takatta','wish','たかった — хотел','Takatta — wanted to','Желание было в прошлом; действие могло и не произойти.','A past desire; the action need not have happened.','たい → たかった, не たいだった.','たい → たかった, not たいだった.','その えいがを みたかったです。','Я хотел посмотреть тот фильм.','I wanted to see that film.'],
    ['takunakatta','wish','たくなかった — не хотел','Takunakatta — did not want to','Отрицание желания в прошлом.','Past negative desire.','たい → たくなかった.','たい → たくなかった.','きのうは はたらきたくなかったです。','Вчера не хотел работать.','I did not want to work yesterday.'],
    ['takute','wish','たくて — хочу, и… / потому что хочу…','Takute — connecting a desire','Соединяет желание со следующей мыслью.','Connect a desire to the next clause.','たい → たくて. Это て-форма конструкции с たい.','たい → たくて. This is the te-form of a tai-expression.','にほんへ いきたくて、にほんごを べんきょうしています。','Учу японский, потому что хочу поехать в Японию.','I am studying Japanese because I want to go to Japan.'],
    ['te-imasu','te','ています — действие / состояние','Te imasu — action / state','Действие сейчас, привычка или результат изменения — зависит от глагола и контекста.','An ongoing action, habit or resulting state, depending on the verb and context.','て-форма + います: よんでいます. すんでいます — живу; しっています — знаю. Отрицание «не знаю»: しりません.','Te-form + います: よんでいます. すんでいます means live; しっています means know. “Do not know” is しりません.','いま、ほんを よんでいます。','Сейчас читаю книгу.','I am reading a book now.'],
    ['te-kudasai','te','てください — сделайте, пожалуйста','Te kudasai — please do','Просьба выполнить действие. Может звучать как указание; не универсально для любой вежливой ситуации.','Ask someone to do something. Can sound like an instruction; not a universal polite request.','て-форма + ください.','Te-form + ください.','ここに なまえを かいてください。','Напишите здесь имя, пожалуйста.','Please write your name here.'],
    ['te-mo-ii','te','てもいいです — можно','Te mo ii — permission','Разрешение; с か — вопрос о разрешении.','Permission; add か to ask permission.','て-форма + もいいです.','Te-form + もいいです.','ここで しゃしんを とってもいいですか。','Можно здесь фотографировать?','May I take photos here?'],
    ['te-wa-ikenai','te','てはいけません — нельзя','Te wa ikemasen — prohibition','Запрет или правило.','A prohibition or rule.','て-форма + はいけません. Частица は читается wa.','Te-form + はいけません. The particle は is pronounced wa.','ここで たばこを すってはいけません。','Здесь нельзя курить.','You must not smoke here.'],
    ['te-kara','te','てから — после того как','Te kara — after doing','Одно действие происходит перед другим.','One action happens before another.','て-форма + から, затем следующее действие.','Te-form + から, followed by the next action.','ごはんを たべてから、でかけます。','Поем, потом выйду из дома.','I will eat, then go out.'],
    ['naide-kudasai','base','ないでください — не делайте','Naide kudasai — please do not','Просьба не делать. Не путай с なくて, которое соединяет отрицание с другой мыслью.','A request not to do something. Different from なくて, which connects a negative clause.','ない-форма + でください: かく → かかないでください.','Nai-form + でください: かく → かかないでください.','ここに かかないでください。','Не пишите здесь, пожалуйста.','Please do not write here.'],
    ['nakereba','base','なければなりません — надо','Nakereba narimasen — must','Обязанность, необходимость.','Obligation or necessity.','ない → なければなりません. Это одна из конструкций обязанности; существуют также ないといけません и другие.','Replace ない with なければなりません. Other obligation expressions include ないといけません.','あした、はやく おきなければなりません。','Завтра надо рано встать.','I must get up early tomorrow.'],
    ['nakutemo','base','なくてもいいです — можно не делать','Nakutemo ii — do not have to','Отсутствие необходимости, а не запрет.','Lack of necessity, not a prohibition.','ない → なくてもいいです.','Replace ない with なくてもいいです.','あしたは こなくてもいいです。','Завтра можно не приходить.','You do not have to come tomorrow.'],
    ['mashou','base','ましょう — давайте','Mashou — let’s','Вежливое предложение сделать что-то вместе.','A polite suggestion to do something together.','Основа ます + ましょう.','Masu stem + ましょう.','いっしょに たべましょう。','Давайте поедим вместе.','Let’s eat together.'],
    ['tara','next','たら — если / когда','Tara — if / when','Условие или событие, после которого случится другое.','A condition or event followed by another event.','た-форма + ら. Здесь た не обязательно означает прошлое.','Ta-form + ら. Here た does not necessarily refer to the past.','じかんが あったら、ほんを よみます。','Если будет время, почитаю книгу.','If I have time, I will read a book.'],
    ['tari','next','たり — действия среди прочего','Tari — actions among others','Неполный список действий. В конце обычно する／します.','A non-exhaustive list of actions, normally ending in する / します.','た-форма + り: よんだり、かいたりします. В задании введи только одну форму на たり／だり.','Ta-form + り: よんだり、かいたりします. Enter just one tari / dari form in the exercise.','やすみの ひは、ほんを よんだり、さんぽしたりします。','В выходной читаю, гуляю и занимаюсь другими делами.','On days off I do things like reading and walking.'],
    ['potential','next','可能形 — могу сделать','Potential — can do','Способность или возможность.','Ability or possibility.','Ⅰ: ряд え + る. Ⅱ: る → られる. Ⅲ: する → できる; くる → こられる. Здесь тренируем полную форму, без разговорного выпадения ら.','Ⅰ: e-row + る. Ⅱ: る → られる. Ⅲ: する → できる; くる → こられる. Practice the full standard form here, retaining ら.','にほんごの ほんが よめます。','Могу читать книги на японском.','I can read books in Japanese.'],
    ['volitional','next','意向形 — сделаем / намерен','Volitional — let’s / intention','Простое предложение или намерение, часто перед と思う.','A casual suggestion or intention, often followed by と思う.','Ⅰ: ряд お + う. Ⅱ: る → よう. Ⅲ: する → しよう; くる → こよう.','Ⅰ: o-row + う. Ⅱ: る → よう. Ⅲ: する → しよう; くる → こよう.','いっしょに いこう。','Пойдём вместе.','Let’s go together.'],
    ['ba','next','ば — если','Ba — conditional','Условие. Употребление отличается от たら; они не всегда взаимозаменяемы.','A condition. Usage differs from たら; they are not always interchangeable.','Ⅰ: ряд え + ば. Ⅱ: る → れば. Ⅲ: する → すれば; くる → くれば.','Ⅰ: e-row + ば. Ⅱ: る → れば. Ⅲ: する → すれば; くる → くれば.','まいにち よめば、だんだん わかります。','Если читать каждый день, постепенно начнёшь понимать.','If you read every day, you will gradually understand.'],
    ['passive','next','受身形 — действие над кем-то','Passive — receiving an action','Субъект испытывает действие. Для употребления нужна отдельная схема участников; одной замены окончания мало.','The subject receives an action. Using it also requires learning how participants are marked.','Ⅰ: ряд あ + れる (う → われる). Ⅱ: る → られる. Ⅲ: する → される; くる → こられる. У Ⅱ совпадает с потенциальной формой.','Ⅰ: a-row + れる (う → われる). Ⅱ: る → られる. Ⅲ: する → される; くる → こられる. Group Ⅱ matches the potential form.','せんせいに ほめられました。','Учитель меня похвалил.','I was praised by the teacher.'],
    ['causative','next','使役形 — заставить / позволить','Causative — make / let','Побуждение или разрешение другому человеку выполнить действие.','Make or let another person perform an action.','Ⅰ: ряд あ + せる (う → わせる). Ⅱ: る → させる. Ⅲ: する → させる; くる → こさせる.','Ⅰ: a-row + せる (う → わせる). Ⅱ: る → させる. Ⅲ: する → させる; くる → こさせる.','こどもを あそばせます。','Даю ребёнку поиграть.','I let the child play.']
  ];
  entries.push(
    ['te-miru','te','てみる — попробовать сделать','Te miru — try doing','Выполнить действие, чтобы узнать результат.','Do something to see how it goes.','て-форма + みる. Вежливо: みます. Здесь вводи простую форму.','Te-form + みる. Polite: みます. Enter the plain form here.','この ほんを よんでみます。','Попробую почитать эту книгу.','I will try reading this book.'],
    ['te-oku','te','ておく — сделать заранее','Te oku — do in advance','Подготовить что-то заранее или оставить в нужном состоянии.','Prepare something in advance or leave it in a desired state.','て-форма + おく. Вежливо: おきます.','Te-form + おく. Polite: おきます.','あしたの きっぷを かっておきます。','Заранее куплю билет на завтра.','I will buy tomorrow’s ticket in advance.'],
    ['te-shimau','te','てしまう — завершить / к сожалению','Te shimau — finish / regret','Полное завершение; в контексте может выражать сожаление или нежелательный результат.','Completion; context can add regret or an unwanted result.','て-форма + しまう. Вежливо: しまいます. Разговорные ちゃう／じゃう пока не тренируем.','Te-form + しまう. Polite: しまいます. Colloquial ちゃう / じゃう are not used in these exercises.','ケーキを ぜんぶ たべてしまいました。','Съел весь торт (возможно, с сожалением).','I ate the whole cake (possibly with regret).'],
    ['te-hoshii','te','てほしい — хочу, чтобы кто-то сделал','Te hoshii — want someone to do','Желание относительно чужого действия. В отличие от たい: действие выполняет другой человек.','Want someone else to perform an action. Unlike たい, another person does it.','て-форма + ほしい. Исполнитель обычно отмечен に. Прямо говорить так старшему может быть невежливо.','Te-form + ほしい. The person performing the action is usually marked with に. A direct request to a superior can sound impolite.','ともだちに てつだってほしいです。','Хочу, чтобы друг помог.','I want my friend to help.']
  );
  const forms=entries.map(([id,section,ru,en,purposeRu,purposeEn,ruleRu,ruleEn,jp,translationRu,translationEn])=>({id,section,ru,en,purpose:pair(purposeRu,purposeEn),rule:pair(ruleRu,ruleEn),example:{jp,...pair(translationRu,translationEn)}}));
  const rows={'う':['わ','い','え','お'],'く':['か','き','け','こ'],'ぐ':['が','ぎ','げ','ご'],'す':['さ','し','せ','そ'],'つ':['た','ち','て','と'],'ぬ':['な','に','ね','の'],'ぶ':['ば','び','べ','ぼ'],'む':['ま','み','め','も'],'る':['ら','り','れ','ろ']};
  function parts(v) {
    const base=v.jp,stem=base.slice(0,-1),row=rows[base.slice(-1)];
    if(v.group==='3'){
      const suru=base.endsWith('する'),prefix=base.slice(0,-2);
      return {masu:prefix+(suru?'し':'き'),nai:prefix+(suru?'しない':'こない'),potential:prefix+(suru?'できる':'こられる'),volitional:prefix+(suru?'しよう':'こよう'),ba:prefix+(suru?'すれば':'くれば'),passive:prefix+(suru?'される':'こられる'),causative:prefix+(suru?'させる':'こさせる')};
    }
    if(v.group==='2')return {masu:stem,nai:stem+'ない',potential:stem+'られる',volitional:stem+'よう',ba:stem+'れば',passive:stem+'られる',causative:stem+'させる'};
    return {masu:stem+row[1],nai:base==='ある'?'ない':stem+row[0]+'ない',potential:stem+row[2]+'る',volitional:stem+row[3]+'う',ba:stem+row[2]+'ば',passive:stem+row[0]+'れる',causative:stem+row[0]+'せる'};
  }
  function conjugate(v,id){
    const p=parts(v),ta=v.te.replace(/て$/,'た').replace(/で$/,'だ');
    const suffix={masu:'ます',masen:'ません',mashita:'ました','masen-deshita':'ませんでした',tai:'たい',takunai:'たくない',takatta:'たかった',takunakatta:'たくなかった',takute:'たくて',mashou:'ましょう'};
    if(suffix[id])return (v.jp==='いらっしゃる' && ['masu','masen','mashita','masen-deshita','mashou'].includes(id)?'いらっしゃい':p.masu)+suffix[id];
    const teSuffix={'te-miru':'みる','te-oku':'おく','te-shimau':'しまう','te-hoshii':'ほしい'};
    if(teSuffix[id])return v.te+teSuffix[id];
    if(p[id])return p[id];
    return {dictionary:v.jp,te:v.te,ta,nakatta:p.nai.slice(0,-1)+'かった','te-imasu':v.te+'います','te-kudasai':v.te+'ください','te-mo-ii':v.te+'もいいです','te-wa-ikenai':v.te+'はいけません','te-kara':v.te+'から','naide-kudasai':p.nai+'でください',nakereba:p.nai.slice(0,-2)+'なければなりません',nakutemo:p.nai.slice(0,-2)+'なくてもいいです',tara:ta+'ら',tari:ta+'り'}[id];
  }
  const samples=[
    {jp:'かう',group:'1',te:'かって'}, {jp:'かく',group:'1',te:'かいて'},
    {jp:'およぐ',group:'1',te:'およいで'}, {jp:'はなす',group:'1',te:'はなして'},
    {jp:'まつ',group:'1',te:'まって'}, {jp:'しぬ',group:'1',te:'しんで'},
    {jp:'あそぶ',group:'1',te:'あそんで'}, {jp:'よむ',group:'1',te:'よんで'},
    {jp:'かえる',group:'1',te:'かえって'},
    {jp:'たべる',group:'2',te:'たべて'}, {jp:'みる',group:'2',te:'みて'},
    {jp:'おきる',group:'2',te:'おきて'}, {jp:'ねる',group:'2',te:'ねて'},
    {jp:'する',group:'3',te:'して'}, {jp:'くる',group:'3',te:'きて'},
    {jp:'コピーする',group:'3',te:'コピーして'}
  ];
  window.IDJLT_FORM_LIBRARY={forms,conjugate,parts,samples};
})();
