const assert = require('node:assert/strict');
const create = require('../study-core.js');
const values = new Map();
const storage = {getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};
let study=create(()=>storage);
const exercise={id:'meaning:apple:ru',ref:'word:apple',answers:['яблоко','яблочко'],answerLanguage:'ru'};
assert.ok(study.check(exercise,' ЯБЛОКО! '));
assert.ok(!study.check(exercise,'не яблоко'));
assert.ok(!study.check(exercise,'яблок'));
assert.ok(study.check({...exercise,answerLanguage:'ja',answers:['ねこ']},'ネコ。'));
assert.deepEqual(study.alternatives('Высокий; дорогой (о цене)'),['Высокий; дорогой (о цене)','Высокий; дорогой','Высокий','дорогой']);
study.record(exercise,{attemptId:'1',correct:false,answer:'груша',now:1000});
assert.equal(study.progressFor(exercise.ref).status,'weak');
assert.equal(study.state.items[exercise.id].due,601000);
assert.equal(study.record(exercise,{attemptId:'1',correct:true,answer:'яблоко'}),false);
assert.equal(study.state.items[exercise.id].errors,1);
assert.ok(study.acceptAlternative(exercise,'1','яблочко красное'));
assert.ok(study.check(exercise,'яблочко красное'));
assert.equal(study.state.items[exercise.id].errors,0);
assert.equal(study.state.items[exercise.id].correct,1);
assert.equal(study.acceptAlternative(exercise,'1','other'),false);
for(let n=2;n<=5;n++)study.record(exercise,{attemptId:String(n),correct:true,answer:'яблоко',now:n*1000});
assert.equal(study.progressFor(exercise.ref).status,'mastered');
study=create(()=>storage);
assert.equal(study.state.items[exercise.id].correct,5);
study.record(exercise,{attemptId:'6',correct:true,assisted:true,answer:'яблоко',now:10000});
assert.equal(study.progressFor(exercise.ref).status,'weak');
assert.equal(study.state.items[exercise.id].streak,0);
const other={...exercise,id:'other',ref:'word:other'};
assert.equal(study.select([exercise,other],{review:true})[0].id,exercise.id);
assert.equal(study.select([exercise,{...exercise,id:'reverse'},other],{count:10}).length,2);
study.markDifficult(other.ref);assert.equal(study.progressFor(other.ref).status,'weak');
study.markDifficult(other.ref);assert.equal(study.progressFor(other.ref).status,'new');
const broken=create(()=>({getItem(){return '{bad'},setItem(){throw Error('quota')}}));
broken.record(exercise,{attemptId:'1',correct:false,answer:'x'});
assert.ok(broken.persistenceError);assert.equal(broken.progressFor(exercise.ref).errors,1);
broken.write('session',{index:3});assert.equal(broken.read('session',null).index,3);
const hostile=JSON.parse('{"version":1,"flags":{"__proto__":true},"items":{"constructor":{"ref":"x"}}}');
assert.equal(Object.keys(study.sanitize(hostile).items).length,0);
assert.equal(Object.keys(study.sanitize(hostile).flags).length,0);
console.log('PASS: normalization, exact alternatives, idempotency, regrading, scheduling, progression, reload, storage failure and data validation.');
